# library
library(ggplot2)

lkVisual <- read.csv('lk_data.csv', colClasses=c(nodes="character"))

pdf(file = "cpuTimeNodes.pdf")
ggplot(lkVisual, aes(x=factor(nodes, level=c('10', '20', '40', '80', '100')), y=meanCpuTime, group = 1)) +
    scale_x_discrete("Nodes")+
    geom_point() +
    ggtitle("CPU time against nodes") +
    ylab("Time (seconds)") +
    geom_smooth()
dev.off()

milpVisual <- read.csv('milp_data.csv', colClasses=c(nodes="character"))
names(lkVisual)[9] ="cpuTime"
lkVisual$Algorithm <- "Lin-Kernighan"
milpVisual$Algorithm <- "MILP"
common <- intersect(colnames(lkVisual), colnames(milpVisual))
visuals = rbind(lkVisual[common], milpVisual[common])

base_breaks <- function(n = 10){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
    }
}

pdf(file = "cpuTimeNodesMerge.pdf")
ggplot(visuals, aes(x=factor(nodes, level=c('10', '20', '40', '80', '100')), y=cpuTime, group=Algorithm, col=Algorithm, fill=Algorithm)) +
    scale_x_discrete("Nodes")+
    geom_point() +
    ggtitle("CPU time against nodes, merged with MILP results") +
    ylab("Time (seconds)") +
    scale_y_log10(breaks = base_breaks(), labels = prettyNum) +
    geom_smooth()
dev.off()

names(lkVisual)[9] ="time"
names(milpVisual)[4] ="time"
common <- intersect(colnames(lkVisual), colnames(milpVisual))
visuals <- rbind(lkVisual[common], milpVisual[common])

pdf(file = "cpuAndUserTimeNodesMerge.pdf")
ggplot(visuals, aes(x=factor(nodes, level=c('10', '20', '40', '80', '100')), y=time, group=Algorithm, col=Algorithm, fill=Algorithm)) +
    scale_x_discrete("Nodes")+
    geom_point() +
    ggtitle("LK time and MILP user time against nodes") +
    ylab("Time (seconds)") +
    scale_y_log10(breaks = base_breaks(), labels = prettyNum) +
    geom_smooth()
dev.off()

fun1 <- function(x, y) (x/y) * 100
lkVisual$relstd <- mapply(fun1, lkVisual$stdDevCost, lkVisual$meanCost)

pdf(file = "relStdDev.pdf")
p <- ggplot(lkVisual, aes(x=factor(nodes, level=c('10', '20', '40', '80', '100')), y=relstd, group=1)) +
    scale_x_discrete("Nodes")+
    geom_point() +
    ggtitle("Relative std deviation of results generated by LK") +
    ylab("Relative std deviation (percentage)") +
    scale_y_log10(breaks = base_breaks(), labels = prettyNum) +
    geom_smooth()

print(p)
dev.off()
