# library
library(ggplot2)

lkVisual <- read.csv('lk_data.csv')
milpVisual <- read.csv('milp_data.csv')

p <- ggplot(lkVisual, aes(x=nodes, y=meanCpuTime, group = 1)) +
    xlab("Nodes") +
    scale_x_continuous(breaks =c(10, 20, 40, 80, 100)) +
    geom_point() +
    ggtitle("CPU time against nodes") +
    ylab("Time (seconds)") +
    geom_smooth()
ggsave(plot = p, width = 5, height = 3, dpi = 300, filename = "cpuTimeNodes.pdf")


names(lkVisual)[9] ="cpuTime"
lkVisual$Algorithm <- "Lin-Kernighan"
milpVisual$Algorithm <- "MILP"
common <- intersect(colnames(lkVisual), colnames(milpVisual))
visuals = rbind(lkVisual[common], milpVisual[common])

base_breaks <- function(n = 10){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
    }
}

p <- ggplot(visuals, aes(x=nodes, y=cpuTime, group=Algorithm, col=Algorithm, fill=Algorithm)) +
    xlab("Nodes")+
    scale_x_continuous(breaks =c(10, 20, 40, 80, 100)) +
    geom_point() +
    ggtitle("CPU time against nodes, merged with MILP results") +
    ylab("Time (seconds)") +
    scale_y_log10(breaks = base_breaks(), labels = prettyNum) +
    geom_smooth()
ggsave(plot = p, width = 5, height = 3, dpi = 300, filename = "cpuTimeNodesMerge.pdf")

names(lkVisual)[9] ="time"
names(milpVisual)[4] ="time"
common <- intersect(colnames(lkVisual), colnames(milpVisual))
visuals <- rbind(lkVisual[common], milpVisual[common])

p <- ggplot(visuals, aes(x=nodes, y=time, group=Algorithm, col=Algorithm, fill=Algorithm)) +
    xlab("Nodes")+
    geom_point() +
    scale_x_continuous(breaks =c(10, 20, 40, 80, 100)) +
    ggtitle("LK time and MILP user time against nodes") +
    ylab("Time (seconds)") +
    scale_y_log10(breaks = base_breaks(), labels = prettyNum) +
    geom_smooth()
ggsave(plot = p, width = 5, height = 3, dpi = 300, filename = "cpuAndUserTimeNodesMerge.pdf")

fun1 <- function(x, y) (x/y) * 100
lkVisual$relstd <- mapply(fun1, lkVisual$stdDevCost, lkVisual$meanCost)

p <- ggplot(lkVisual, aes(x=nodes, y=relstd, group=1)) +
    xlab("Nodes") +
    scale_x_continuous(breaks =c(10, 20, 40, 80, 100)) +
    geom_point() +
    ggtitle("Relative std deviation of results generated by LK") +
    ylab("Relative std deviation (percentage)") +
    scale_y_log10(breaks = base_breaks(), labels = prettyNum) +
    geom_smooth()
ggsave(plot = p, width = 5, height = 3, dpi = 300, filename = "relStdDev.pdf")
